image: registry.stuhome.com/devops/dockerepo/docker:1.0.1

services:
    - docker:18.09.7-dind

variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    GIT_SUBMODULE_STRATEGY: recursive
    ENV: ci

stages:
  - test
  - package

test-build-image:
    stage: test

    script:
    - ./install.sh /opt/runtime
    - source runtime_env
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - runtime_image_base_image alpine:3.7
    - build_runtime_image gitlab-docker -t gitlab_ci_commit_hash -e ENV

test-build-lnmp-image:
    stage: test
    script:
    - ./install.sh /opt/runtime
    - source runtime_env
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - runtime_image_base_image php:7.2-fpm-alpine
    - runtime_image_post_build_script ci/ci_lnmp_postbuild.sh
    - runtime_image_add_service normal php_fpm /usr/local/sbin/php-fpm
    - runtime_image_add_service normal nginx /usr/sbin/nginx -g 'daemon off;'
    - build_runtime_image gitlab-docker -t gitlab_ci_commit_hash -e ENV
    variables:
        ENV: ci_lnmp


package-manifests:
    stage: package

    script:
    - ./install.sh /opt/runtime
    - source runtime_env
    - rm .gitlab-ci.yml 
    - ci_build gitlab-package -t gitlab_ci_commit_hash -e CI_COMMIT_REF_NAME ./

    allow_failure: false
