image: registry.stuhome.com/devops/dockerepo/docker:1.0.1

stages:
  - package

package-manifests:
    stage: package
    services:
        - docker:18.09.7-dind

    variables:
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay2
        GIT_SUBMODULE_STRATEGY: recursive

    script:
    - ./install.sh /opt/runtime
    - source runtime_env
    - rm .gitlab-ci.yml 
    - ci_build gitlab-package -t gitlab_ci_commit_hash -e CI_COMMIT_REF_NAME ./

    allow_failure: false
