image: registry.stuhome.com/devops/dockerepo/docker:1.0.1

before_script:
  - ./install.sh /opt/runtime
  - source runtime_env

services:
    - docker:18.09.7-dind

variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    GIT_SUBMODULE_STRATEGY: recursive
    ENV: ci

stages:
  - package
  - test

test-build-image:
    stage: test

    script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - runtime_image_base_image alpine:3.7
    - build_runtime_image gitlab-docker -t gitlab_ci_commit_hash -e ENV

test-build-lnmp-image:
    stage: test
    script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - runtime_image_base_image php:7.2-fpm-alpine
    - runtime_image_post_build_script ci/ci_lnmp_postbuild.sh
    - runtime_image_add_service normal php_fpm /usr/local/sbin/php-fpm
    - runtime_image_add_service normal nginx /usr/sbin/nginx -g 'daemon off;'
    - build_runtime_image gitlab-docker -h ci/ci_lnmp_postbuild.sh -e ENV --ignore-runtime
    variables:
        ENV: ci_lnmp

test-pull-package:
    stage: test
    script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - ci_package_pull -r devops/runtime -e CI_COMMIT_REF_NAME ./testing_pull

test-no-push:
    stage: test
    script:
    - source ci/docker_push_gate.sh
    - runtime_image_base_image registry.stuhome.com/devops/dockerepo/alpine:3.7
    - build_runtime_image gitlab-docker -t gitlab_ci_commit_hash -e ENV -s -f
    - ci_build gitlab-package -t gitlab_ci_commit_hash -e CI_COMMIT_REF_NAME -s -f ./


package-manifests:
    stage: package

    script:
    - rm .gitlab-ci.yml 
    - ci_build gitlab-package -e CI_COMMIT_REF_NAME ./

    allow_failure: false
