bind: 0.0.0.0:8077
database:
  dsn: "root:123456@tcp(127.0.0.1:3306)/wing?charset=utf8&parseTime=true"
  engine: mysql

kubernetes:
  namespace: default
  kubeConfig: ./config

auth:
  enableLDAP: true
  disableLegacyUser: false

  ldap:
     server: 10.240.5.1:389
     bindDN: cn=admin,dc=starstudio,dc=com
     bindPassword: testing_ldap
     baseDN: dc=starstudio,dc=com
     searchPattern: (&(objectClass=person)(cn={0}))
     nameAttribute: cn
     #syncLegacyUser: false
