bind: 0.0.0.0:8077
database:
  dsn: "root:123456@tcp(127.0.0.1:3306)/wing?charset=utf8&parseTime=true"
  engine: mysql

kubernetes:
  namespace: default
  kubeConfig: ./config

ldap:
   server: 10.240.5.1:389
   adminUser: cn=admin,dc=starstudio,dc=com
   baseDN: dc=starstudio,dc=com
   searchPatten: (&(objectClass=person)(cn={0}))
   nameAttribute: cn
