bind: 0.0.0.0:8077
database:
  dsn: "root:123456@tcp(127.0.0.1:3306)/wing?charset=utf8&parseTime=true"
  engine: mysql

kubernetes:
  namespace: default
  kubeConfig: ./config

auth:
  enableLDAP: true
  disableLegacyUser: false

  ldap:
     server: 10.240.5.1:389
     bindDN: cn=admin,dc=starstudio,dc=com
     bindPassword: testing_password
     baseDN: dc=starstudio,dc=com
     searchPattern: (&(objectClass=person)(cn=%v))
     nameAttribute: cn
     #syncLegacyUser: false
     acceptRegistration: false
     registerRDN: cn=%v
     registerObjectClasses:
       - person
     registerAttributes:
       sn: "%[1]v"
     
