FROM alpine:3.6

ARG APK_MIRROR=mirror.tuna.tsinghua.edu.cn

RUN set -xe;\
    sed -Ei "s/dl-cdn\.alpinelinux\.org/$APK_MIRROR/g" /etc/apk/repositories; \
    mkdir /apk-cache;\
    apk update --cache-dir /apk-cache && apk add bash jq gettext --cache-dir /apk-cache;\
    rm -rf /apk-cache

CMD ["/bin/bash"]