FROM php:7.2-fpm-alpine

RUN set -xe;\
    sed -Ei "s/dl-cdn\.alpinelinux\.org/$APK_MIRROR/g" /etc/apk/repositories; \
    mkdir /apk-cache;\
    apk update --cache-dir /apk-cache && apk add bash jq gettext --cache-dir /apk-cache;\
    rm -rf /apk-cache