bind: 0.0.0.0:8077
externalURL: http://wing.starstudio.org/

database:
  dsn: "root:123456@tcp(127.0.0.1:8062)/wing?charset=utf8&parseTime=true"
  engine: mysql

kubernetes:
  namespace: default
  kubeConfig: ./config

session:
  job:
    brokerType: redis
    address: 127.0.0.1
    port: 8061
    gitWorkingDir: ./testrepo/

auth:
  enableLDAP: true
  disableLegacyUser: false

  ldap:
     server: 10.240.5.1:389
     bindDN: cn=admin,dc=starstudio,dc=com
     bindPassword: testing_password
     baseDN: dc=starstudio,dc=com
     searchPattern: (&(objectClass=person)(cn=%v))
     nameAttribute: cn
     #syncLegacyUser: false
     acceptRegistration: false
     registerRDN: cn=%v
     registerObjectClasses:
       - person
     registerAttributes:
       sn: "%[1]v"