bind: 0.0.0.0:8077
externalURL: http://127.0.0.1:8077/

database:
  user: root
  password: "123456"
  database: wing
  charset: utf8
  engine: mysql
  address: 127.0.0.1
  port: 8062
  options:
    charset: utf8

kubernetes:
  namespace: default
  kubeConfig: ./config

session:
  job:
    brokerType: redis
    address: 127.0.0.1
    port: 8061
    gitWorkingDir: ./docker/repos

auth:
  enableLDAP: true
  disableLegacyUser: false

  ldap:
     server: 10.240.5.1:389
     bindDN: cn=admin,dc=starstudio,dc=com
     bindPassword: testing_password
     baseDN: dc=starstudio,dc=com
     searchPattern: (&(objectClass=person)(cn=%v))
     nameAttribute: cn
     #syncLegacyUser: false
     acceptRegistration: false
     registerRDN: cn=%v
     registerObjectClasses:
       - person
     registerAttributes:
       sn: "%[1]v"
